// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rdgnqpsvlbsoyynbwrza.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkZ25xcHN2bGJzb3l5bmJ3cnphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5ODY1NzAsImV4cCI6MjA1NjU2MjU3MH0.-t3KhvuZjoJPSdv8vDi66K_uUV07JSNsXersnLb6eNE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);